# Multi-Region Failover Configuration
# This extends the main docker-compose.yml with failover DNS servers

services:
  # Backup DNS server (Cloud-based) - Region 1
  dns-backup-cloud1:
    image: coredns/coredns:latest
    container_name: dns-backup-cloud1
    hostname: dns-backup-cloud1
    restart: unless-stopped
    ports:
      - "5380:53/udp"
      - "5380:53/tcp"
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/zones:/zones:ro
    command: -conf /Corefile
    healthcheck:
      test: ["CMD", "coredns", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    environment:
      - PRIMARY_DNS=192.168.8.251
      - SECONDARY_DNS=192.168.8.252
      - REGION=cloud1

  # Backup DNS server (Cloud-based) - Region 2
  dns-backup-cloud2:
    image: coredns/coredns:latest
    container_name: dns-backup-cloud2
    hostname: dns-backup-cloud2
    restart: unless-stopped
    ports:
      - "5381:53/udp"
      - "5381:53/tcp"
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/zones:/zones:ro
    command: -conf /Corefile
    healthcheck:
      test: ["CMD", "coredns", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    environment:
      - PRIMARY_DNS=192.168.8.251
      - SECONDARY_DNS=192.168.8.252
      - REGION=cloud2

  # Failover coordinator
  dns-failover-manager:
    build: ./failover-manager
    container_name: dns-failover-manager
    hostname: failover-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./failover-manager:/app:ro
    environment:
      - CHECK_INTERVAL=30
      - PRIMARY_DNS=192.168.8.251
      - SECONDARY_DNS=192.168.8.252
      - BACKUP_DNS_1=127.0.0.1:5380
      - BACKUP_DNS_2=127.0.0.1:5381
      - CLOUD_DNS_1=${CLOUD_DNS_1:-8.8.8.8}
      - CLOUD_DNS_2=${CLOUD_DNS_2:-1.1.1.1}
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  default:
    name: observability_net
    external: true
